-- Table structure for table `countries`

DROP TABLE IF EXISTS `countries`;
CREATE TABLE `countries` (
  `countries_id` mediumint unsigned NOT NULL AUTO_INCREMENT,
  `countries_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `countries_code` char(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `countries_currency` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `countries_currency_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `countries_currency_symbol` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `countries_region` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `countries_subregion` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`countries_id`)
) ENGINE=InnoDB AUTO_INCREMENT=251 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Dumping data for table `countries`
INSERT INTO `countries` VALUES
(1,'Afghanistan','AF','AFN','Afghan afghani','؋','Asia','Southern Asia'),
(2,'Aland Islands','AX','EUR','Euro','€','Europe','Northern Europe'),
(3,'Albania','AL','ALL','Albanian lek','Lek','Europe','Southern Europe'),
(4,'Algeria','DZ','DZD','Algerian dinar','دج','Africa','Northern Africa'),
(5,'American Samoa','AS','USD','US Dollar','$','Oceania','Polynesia'),
(6,'Andorra','AD','EUR','Euro','€','Europe','Southern Europe'),
(7,'Angola','AO','AOA','Angolan kwanza','Kz','Africa','Middle Africa'),
(8,'Anguilla','AI','XCD','East Caribbean dollar','$','Americas','Caribbean'),
(9,'Antarctica','AQ','AAD','Antarctican dollar','$','Polar',''),
(10,'Antigua And Barbuda','AG','XCD','Eastern Caribbean dollar','$','Americas','Caribbean'),
(11,'Argentina','AR','ARS','Argentine peso','$','Americas','South America'),
(12,'Armenia','AM','AMD','Armenian dram','֏','Asia','Western Asia'),
(13,'Aruba','AW','AWG','Aruban florin','ƒ','Americas','Caribbean'),
(14,'Australia','AU','AUD','Australian dollar','$','Oceania','Australia and New Zealand'),
(15,'Austria','AT','EUR','Euro','€','Europe','Western Europe'),
(16,'Azerbaijan','AZ','AZN','Azerbaijani manat','m','Asia','Western Asia'),
(17,'The Bahamas','BS','BSD','Bahamian dollar','B$','Americas','Caribbean'),
(18,'Bahrain','BH','BHD','Bahraini dinar','.د.ب','Asia','Western Asia'),
(19,'Bangladesh','BD','BDT','Bangladeshi taka','৳','Asia','Southern Asia'),
(20,'Barbados','BB','BBD','Barbadian dollar','Bds$','Americas','Caribbean'),
(21,'Belarus','BY','BYN','Belarusian ruble','Br','Europe','Eastern Europe'),
(22,'Belgium','BE','EUR','Euro','€','Europe','Western Europe'),
(23,'Belize','BZ','BZD','Belize dollar','$','Americas','Central America'),
(24,'Benin','BJ','XOF','West African CFA franc','CFA','Africa','Western Africa'),
(25,'Bermuda','BM','BMD','Bermudian dollar','$','Americas','Northern America'),
(26,'Bhutan','BT','BTN','Bhutanese ngultrum','Nu.','Asia','Southern Asia'),
(27,'Bolivia','BO','BOB','Bolivian boliviano','Bs.','Americas','South America'),
(28,'Bosnia and Herzegovina','BA','BAM','Bosnia and Herzegovina convertible mark','KM','Europe','Southern Europe'),
(29,'Botswana','BW','BWP','Botswana pula','P','Africa','Southern Africa'),
(30,'Bouvet Island','BV','NOK','Norwegian Krone','kr','',''),
(31,'Brazil','BR','BRL','Brazilian real','R$','Americas','South America'),
(32,'British Indian Ocean Territory','IO','USD','United States dollar','$','Africa','Eastern Africa'),
(33,'Brunei','BN','BND','Brunei dollar','B$','Asia','South-Eastern Asia'),
(34,'Bulgaria','BG','BGN','Bulgarian lev','Лв.','Europe','Eastern Europe'),
(35,'Burkina Faso','BF','XOF','West African CFA franc','CFA','Africa','Western Africa'),
(36,'Burundi','BI','BIF','Burundian franc','FBu','Africa','Eastern Africa'),
(37,'Cambodia','KH','KHR','Cambodian riel','KHR','Asia','South-Eastern Asia'),
(38,'Cameroon','CM','XAF','Central African CFA franc','FCFA','Africa','Middle Africa'),
(39,'Canada','CA','CAD','Canadian dollar','$','Americas','Northern America'),
(40,'Cape Verde','CV','CVE','Cape Verdean escudo','$','Africa','Western Africa'),
(41,'Cayman Islands','KY','KYD','Cayman Islands dollar','$','Americas','Caribbean'),
(42,'Central African Republic','CF','XAF','Central African CFA franc','FCFA','Africa','Middle Africa'),
(43,'Chad','TD','XAF','Central African CFA franc','FCFA','Africa','Middle Africa'),
(44,'Chile','CL','CLP','Chilean peso','$','Americas','South America'),
(45,'China','CN','CNY','Chinese yuan','¥','Asia','Eastern Asia'),
(46,'Christmas Island','CX','AUD','Australian dollar','$','Oceania','Australia and New Zealand'),
(47,'Cocos Keeling Islands','CC','AUD','Australian dollar','$','Oceania','Australia and New Zealand'),
(48,'Colombia','CO','COP','Colombian peso','$','Americas','South America'),
(49,'Comoros','KM','KMF','Comorian franc','CF','Africa','Eastern Africa'),
(50,'Congo','CG','XAF','Central African CFA franc','FC','Africa','Middle Africa'),
(51,'Democratic Republic of the Congo','CD','CDF','Congolese Franc','FC','Africa','Middle Africa'),
(52,'Cook Islands','CK','NZD','Cook Islands dollar','$','Oceania','Polynesia'),
(53,'Costa Rica','CR','CRC','Costa Rican colón','₡','Americas','Central America'),
(54,'Cote D\'Ivoire Ivory Coast','CI','XOF','West African CFA franc','CFA','Africa','Western Africa'),
(55,'Croatia','HR','HRK','Croatian kuna','kn','Europe','Southern Europe'),
(56,'Cuba','CU','CUP','Cuban peso','$','Americas','Caribbean'),
(57,'Cyprus','CY','EUR','Euro','€','Europe','Southern Europe'),
(58,'Czech Republic','CZ','CZK','Czech koruna','Kč','Europe','Eastern Europe'),
(59,'Denmark','DK','DKK','Danish krone','Kr.','Europe','Northern Europe'),
(60,'Djibouti','DJ','DJF','Djiboutian franc','Fdj','Africa','Eastern Africa'),
(61,'Dominica','DM','XCD','Eastern Caribbean dollar','$','Americas','Caribbean'),
(62,'Dominican Republic','DO','DOP','Dominican peso','$','Americas','Caribbean'),
(63,'East Timor','TL','USD','United States dollar','$','Asia','South-Eastern Asia'),
(64,'Ecuador','EC','USD','United States dollar','$','Americas','South America'),
(65,'Egypt','EG','EGP','Egyptian pound','ج.م','Africa','Northern Africa'),
(66,'El Salvador','SV','USD','United States dollar','$','Americas','Central America'),
(67,'Equatorial Guinea','GQ','XAF','Central African CFA franc','FCFA','Africa','Middle Africa'),
(68,'Eritrea','ER','ERN','Eritrean nakfa','Nfk','Africa','Eastern Africa'),
(69,'Estonia','EE','EUR','Euro','€','Europe','Northern Europe'),
(70,'Ethiopia','ET','ETB','Ethiopian birr','Nkf','Africa','Eastern Africa'),
(71,'Falkland Islands','FK','FKP','Falkland Islands pound','£','Americas','South America'),
(72,'Faroe Islands','FO','DKK','Danish krone','Kr.','Europe','Northern Europe'),
(73,'Fiji Islands','FJ','FJD','Fijian dollar','FJ$','Oceania','Melanesia'),
(74,'Finland','FI','EUR','Euro','€','Europe','Northern Europe'),
(75,'France','FR','EUR','Euro','€','Europe','Western Europe'),
(76,'French Guiana','GF','EUR','Euro','€','Americas','South America'),
(77,'French Polynesia','PF','XPF','CFP franc','₣','Oceania','Polynesia'),
(78,'French Southern Territories','TF','EUR','Euro','€','Africa','Southern Africa'),
(79,'Gabon','GA','XAF','Central African CFA franc','FCFA','Africa','Middle Africa'),
(80,'Gambia The','GM','GMD','Gambian dalasi','D','Africa','Western Africa'),
(81,'Georgia','GE','GEL','Georgian lari','ლ','Asia','Western Asia'),
(82,'Germany','DE','EUR','Euro','€','Europe','Western Europe'),
(83,'Ghana','GH','GHS','Ghanaian cedi','GH₵','Africa','Western Africa'),
(84,'Gibraltar','GI','GIP','Gibraltar pound','£','Europe','Southern Europe'),
(85,'Greece','GR','EUR','Euro','€','Europe','Southern Europe'),
(86,'Greenland','GL','DKK','Danish krone','Kr.','Americas','Northern America'),
(87,'Grenada','GD','XCD','Eastern Caribbean dollar','$','Americas','Caribbean'),
(88,'Guadeloupe','GP','EUR','Euro','€','Americas','Caribbean'),
(89,'Guam','GU','USD','US Dollar','$','Oceania','Micronesia'),
(90,'Guatemala','GT','GTQ','Guatemalan quetzal','Q','Americas','Central America'),
(91,'Guernsey and Alderney','GG','GBP','British pound','£','Europe','Northern Europe'),
(92,'Guinea','GN','GNF','Guinean franc','FG','Africa','Western Africa'),
(93,'Guinea-Bissau','GW','XOF','West African CFA franc','CFA','Africa','Western Africa'),
(94,'Guyana','GY','GYD','Guyanese dollar','$','Americas','South America'),
(95,'Haiti','HT','HTG','Haitian gourde','G','Americas','Caribbean'),
(96,'Heard Island and McDonald Islands','HM','AUD','Australian dollar','$','',''),
(97,'Honduras','HN','HNL','Honduran lempira','L','Americas','Central America'),
(98,'Hong Kong S.A.R.','HK','HKD','Hong Kong dollar','$','Asia','Eastern Asia'),
(99,'Hungary','HU','HUF','Hungarian forint','Ft','Europe','Eastern Europe'),
(100,'Iceland','IS','ISK','Icelandic króna','kr','Europe','Northern Europe'),
(101,'India','IN','INR','Indian rupee','₹','Asia','Southern Asia'),
(102,'Indonesia','ID','IDR','Indonesian rupiah','Rp','Asia','South-Eastern Asia'),
(103,'Iran','IR','IRR','Iranian rial','﷼','Asia','Southern Asia'),
(104,'Iraq','IQ','IQD','Iraqi dinar','د.ع','Asia','Western Asia'),
(105,'Ireland','IE','EUR','Euro','€','Europe','Northern Europe'),
(106,'Israel','IL','ILS','Israeli new shekel','₪','Asia','Western Asia'),
(107,'Italy','IT','EUR','Euro','€','Europe','Southern Europe'),
(108,'Jamaica','JM','JMD','Jamaican dollar','J$','Americas','Caribbean'),
(109,'Japan','JP','JPY','Japanese yen','¥','Asia','Eastern Asia'),
(110,'Jersey','JE','GBP','British pound','£','Europe','Northern Europe'),
(111,'Jordan','JO','JOD','Jordanian dinar','ا.د','Asia','Western Asia'),
(112,'Kazakhstan','KZ','KZT','Kazakhstani tenge','лв','Asia','Central Asia'),
(113,'Kenya','KE','KES','Kenyan shilling','KSh','Africa','Eastern Africa'),
(114,'Kiribati','KI','AUD','Australian dollar','$','Oceania','Micronesia'),
(115,'North Korea','KP','KPW','North Korean Won','₩','Asia','Eastern Asia'),
(116,'South Korea','KR','KRW','Won','₩','Asia','Eastern Asia'),
(117,'Kuwait','KW','KWD','Kuwaiti dinar','ك.د','Asia','Western Asia'),
(118,'Kyrgyzstan','KG','KGS','Kyrgyzstani som','лв','Asia','Central Asia'),
(119,'Laos','LA','LAK','Lao kip','₭','Asia','South-Eastern Asia'),
(120,'Latvia','LV','EUR','Euro','€','Europe','Northern Europe'),
(121,'Lebanon','LB','LBP','Lebanese pound','£','Asia','Western Asia'),
(122,'Lesotho','LS','LSL','Lesotho loti','L','Africa','Southern Africa'),
(123,'Liberia','LR','LRD','Liberian dollar','$','Africa','Western Africa'),
(124,'Libya','LY','LYD','Libyan dinar','د.ل','Africa','Northern Africa'),
(125,'Liechtenstein','LI','CHF','Swiss franc','CHf','Europe','Western Europe'),
(126,'Lithuania','LT','EUR','Euro','€','Europe','Northern Europe'),
(127,'Luxembourg','LU','EUR','Euro','€','Europe','Western Europe'),
(128,'Macau S.A.R.','MO','MOP','Macanese pataca','$','Asia','Eastern Asia'),
(129,'Macedonia','MK','MKD','Denar','ден','Europe','Southern Europe'),
(130,'Madagascar','MG','MGA','Malagasy ariary','Ar','Africa','Eastern Africa'),
(131,'Malawi','MW','MWK','Malawian kwacha','MK','Africa','Eastern Africa'),
(132,'Malaysia','MY','MYR','Malaysian ringgit','RM','Asia','South-Eastern Asia'),
(133,'Maldives','MV','MVR','Maldivian rufiyaa','Rf','Asia','Southern Asia'),
(134,'Mali','ML','XOF','West African CFA franc','CFA','Africa','Western Africa'),
(135,'Malta','MT','EUR','Euro','€','Europe','Southern Europe'),
(136,'Man Isle of','IM', 'Isle of Man','GBP','British pound','Isle of Man','Europe'),
(137,'Marshall Islands','MH','USD','United States dollar','$','Oceania','Micronesia'),
(138,'Martinique','MQ','EUR','Euro','€','Americas','Caribbean'),
(139,'Mauritania','MR','MRO','Mauritanian ouguiya','MRU','Africa','Western Africa'),
(140,'Mauritius','MU','MUR','Mauritian rupee','₨','Africa','Eastern Africa'),
(141,'Mayotte','YT','EUR','Euro','€','Africa','Eastern Africa'),
(142,'Mexico','MX','MXN','Mexican peso','$','Americas','Central America'),
(143,'Micronesia','FM','USD','United States dollar','$','Oceania','Micronesia'),
(144,'Moldova','MD','MDL','Moldovan leu','L','Europe','Eastern Europe'),
(145,'Monaco','MC','EUR','Euro','€','Europe','Western Europe'),
(146,'Mongolia','MN','MNT','Mongolian tögrög','₮','Asia','Eastern Asia'),
(147,'Montenegro','ME','EUR','Euro','€','Europe','Southern Europe'),
(148,'Montserrat','MS','XCD','Eastern Caribbean dollar','$','Americas','Caribbean'),
(149,'Morocco','MA','MAD','Moroccan dirham','DH','Africa','Northern Africa'),
(150,'Mozambique','MZ','MZN','Mozambican metical','MT','Africa','Eastern Africa'),
(151,'Myanmar','MM','MMK','Burmese kyat','K','Asia','South-Eastern Asia'),
(152,'Namibia','NA','NAD','Namibian dollar','$','Africa','Southern Africa'),
(153,'Nauru','NR','AUD','Australian dollar','$','Oceania','Micronesia'),
(154,'Nepal','NP','NPR','Nepalese rupee','₨','Asia','Southern Asia'),
(155,'Bonaire','535','Kralendijk','USD','United States dollar','Caribisch Nederland','Americas'),
(156,'Netherlands','NL','EUR','Euro','€','Europe','Western Europe'),
(157,'New Caledonia','NC','XPF','CFP franc','₣','Oceania','Melanesia'),
(158,'New Zealand','NZ','NZD','New Zealand dollar','$','Oceania','Australia and New Zealand'),
(159,'Nicaragua','NI','NIO','Nicaraguan córdoba','C$','Americas','Central America'),
(160,'Niger','NE','XOF','West African CFA franc','CFA','Africa','Western Africa'),
(161,'Nigeria','NG','NGN','Nigerian naira','₦','Africa','Western Africa'),
(162,'Niue','NU','NZD','New Zealand dollar','$','Oceania','Polynesia'),
(163,'Norfolk Island','NF','AUD','Australian dollar','$','Oceania','Australia and New Zealand'),
(164,'Northern Mariana Islands','MP','USD','United States dollar','$','Oceania','Micronesia'),
(165,'Norway','NO','NOK','Norwegian krone','kr','Europe','Northern Europe'),
(166,'Oman','OM','OMR','Omani rial','.ع.ر','Asia','Western Asia'),
(167,'Pakistan','PK','PKR','Pakistani rupee','₨','Asia','Southern Asia'),
(168,'Palau','PW','USD','United States dollar','$','Oceania','Micronesia'),
(169,'Palestinian Territory Occupied','PS','ILS','Israeli new shekel','₪','Asia','Western Asia'),
(170,'Panama','PA','PAB','Panamanian balboa','B/.','Americas','Central America'),
(171,'Papua new Guinea','PG','PGK','Papua New Guinean kina','K','Oceania','Melanesia'),
(172,'Paraguay','PY','PYG','Paraguayan guarani','₲','Americas','South America'),
(173,'Peru','PE','PEN','Peruvian sol','S/.','Americas','South America'),
(174,'Philippines','PH','PHP','Philippine peso','₱','Asia','South-Eastern Asia'),
(175,'Pitcairn Island','PN','NZD','New Zealand dollar','$','Oceania','Polynesia'),
(176,'Poland','PL','PLN','Polish złoty','zł','Europe','Eastern Europe'),
(177,'Portugal','PT','EUR','Euro','€','Europe','Southern Europe'),
(178,'Puerto Rico','PR','USD','United States dollar','$','Americas','Caribbean'),
(179,'Qatar','QA','QAR','Qatari riyal','ق.ر','Asia','Western Asia'),
(180,'Reunion','RE','EUR','Euro','€','Africa','Eastern Africa'),
(181,'Romania','RO','RON','Romanian leu','lei','Europe','Eastern Europe'),
(182,'Russia','RU','RUB','Russian ruble','₽','Europe','Eastern Europe'),
(183,'Rwanda','RW','RWF','Rwandan franc','FRw','Africa','Eastern Africa'),
(184,'Saint Helena','SH','SHP','Saint Helena pound','£','Africa','Western Africa'),
(185,'Saint Kitts And Nevis','KN','XCD','Eastern Caribbean dollar','$','Americas','Caribbean'),
(186,'Saint Lucia','LC','XCD','Eastern Caribbean dollar','$','Americas','Caribbean'),
(187,'Saint Pierre and Miquelon','PM','EUR','Euro','€','Americas','Northern America'),
(188,'Saint Vincent And The Grenadines','VC','XCD','Eastern Caribbean dollar','$','Americas','Caribbean'),
(189,'Saint-Barthelemy','BL','EUR','Euro','€','Americas','Caribbean'),
(190,'Saint-Martin French part','MF','EUR','Euro','€','Americas','Caribbean'),
(191,'Samoa','WS','WST','Samoan tālā','SAT','Oceania','Polynesia'),
(192,'San Marino','SM','EUR','Euro','€','Europe','Southern Europe'),
(193,'Sao Tome and Principe','ST','STD','Dobra','Db','Africa','Middle Africa'),
(194,'Saudi Arabia','SA','SAR','Saudi riyal','﷼','Asia','Western Asia'),
(195,'Senegal','SN','XOF','West African CFA franc','CFA','Africa','Western Africa'),
(196,'Serbia','RS','RSD','Serbian dinar','din','Europe','Southern Europe'),
(197,'Seychelles','SC','SCR','Seychellois rupee','SRe','Africa','Eastern Africa'),
(198,'Sierra Leone','SL','SLL','Sierra Leonean leone','Le','Africa','Western Africa'),
(199,'Singapore','SG','SGD','Singapore dollar','$','Asia','South-Eastern Asia'),
(200,'Slovakia','SK','EUR','Euro','€','Europe','Eastern Europe'),
(201,'Slovenia','SI','EUR','Euro','€','Europe','Southern Europe'),
(202,'Solomon Islands','SB','SBD','Solomon Islands dollar','Si$','Oceania','Melanesia'),
(203,'Somalia','SO','SOS','Somali shilling','Sh.so.','Africa','Eastern Africa'),
(204,'South Africa','ZA','ZAR','South African rand','R','Africa','Southern Africa'),
(205,'South Georgia','GS','GBP','British pound','£','Americas','South America'),
(206,'South Sudan','SS','SSP','South Sudanese pound','£','Africa','Middle Africa'),
(207,'Spain','ES','EUR','Euro','€','Europe','Southern Europe'),
(208,'Sri Lanka','LK','LKR','Sri Lankan rupee','Rs','Asia','Southern Asia'),
(209,'Sudan','SD','SDG','Sudanese pound','.س.ج','Africa','Northern Africa'),
(210,'Suriname','SR','SRD','Surinamese dollar','$','Americas','South America'),
(211,'Svalbard And Jan Mayen Islands','SJ','NOK','Norwegian Krone','kr','Europe','Northern Europe'),
(212,'Swaziland','SZ','SZL','Lilangeni','E','Africa','Southern Africa'),
(213,'Sweden','SE','SEK','Swedish krona','kr','Europe','Northern Europe'),
(214,'Switzerland','CH','CHF','Swiss franc','CHf','Europe','Western Europe'),
(215,'Syria','SY','SYP','Syrian pound','LS','Asia','Western Asia'),
(216,'Taiwan','TW','TWD','New Taiwan dollar','$','Asia','Eastern Asia'),
(217,'Tajikistan','TJ','TJS','Tajikistani somoni','SM','Asia','Central Asia'),
(218,'Tanzania','TZ','TZS','Tanzanian shilling','TSh','Africa','Eastern Africa'),
(219,'Thailand','TH','THB','Thai baht','฿','Asia','South-Eastern Asia'),
(220,'Togo','TG','XOF','West African CFA franc','CFA','Africa','Western Africa'),
(221,'Tokelau','TK','NZD','New Zealand dollar','$','Oceania','Polynesia'),
(222,'Tonga','TO','TOP','Tongan paʻanga','$','Oceania','Polynesia'),
(223,'Trinidad And Tobago','TT','TTD','Trinidad and Tobago dollar','$','Americas','Caribbean'),
(224,'Tunisia','TN','TND','Tunisian dinar','ت.د','Africa','Northern Africa'),
(225,'Turkey','TR','TRY','Turkish lira','₺','Asia','Western Asia'),
(226,'Turkmenistan','TM','TMT','Turkmenistan manat','T','Asia','Central Asia'),
(227,'Turks And Caicos Islands','TC','USD','United States dollar','$','Americas','Caribbean'),
(228,'Tuvalu','TV','AUD','Australian dollar','$','Oceania','Polynesia'),
(229,'Uganda','UG','UGX','Ugandan shilling','USh','Africa','Eastern Africa'),
(230,'Ukraine','UA','UAH','Ukrainian hryvnia','₴','Europe','Eastern Europe'),
(231,'United Arab Emirates','AE','AED','United Arab Emirates dirham','إ.د','Asia','Western Asia'),
(232,'United Kingdom','GB','GBP','British pound','£','Europe','Northern Europe'),
(233,'United States','US','USD','United States dollar','$','Americas','Northern America'),
(234,'United States Minor Outlying Islands','UM','USD','United States dollar','$','Americas','Northern America'),
(235,'Uruguay','UY','UYU','Uruguayan peso','$','Americas','South America'),
(236,'Uzbekistan','UZ','UZS','Uzbekistani soʻm','лв','Asia','Central Asia'),
(237,'Vanuatu','VU','VUV','Vanuatu vatu','VT','Oceania','Melanesia'),
(238,'Vatican City State Holy See','VA','EUR','Euro','€','Europe','Southern Europe'),
(239,'Venezuela','VE','VEF','Bolívar','Bs','Americas','South America'),
(240,'Vietnam','VN','VND','Vietnamese đồng','₫','Asia','South-Eastern Asia'),
(241,'Virgin Islands British','VG','USD','United States dollar','$','Americas','Caribbean'),
(242,'Virgin Islands US','VI','USD','United States dollar','$','Americas','Caribbean'),
(243,'Wallis And Futuna Islands','WF','XPF','CFP franc','₣','Oceania','Polynesia'),
(244,'Western Sahara','EH','MAD','Moroccan Dirham','MAD','Africa','Northern Africa'),
(245,'Yemen','YE','YER','Yemeni rial','﷼','Asia','Western Asia'),
(246,'Zambia','ZM','ZMW','Zambian kwacha','ZK','Africa','Eastern Africa'),
(247,'Zimbabwe','ZW','ZWL','Zimbabwe Dollar','$','Africa','Eastern Africa'),
(248,'Kosovo','XK','EUR','Euro','€','Europe','Eastern Europe'),
(249,'Curaçao','CW','ANG','Netherlands Antillean guilder','ƒ','Americas','Caribbean'),
(250,'Sint Maarten Dutch part','SX','ANG','Netherlands Antillean guilder','ƒ','Americas','Caribbean');